import turtle
turtle.shape("turtle")
turtle.fillcolor("red")
turtle.bgcolor("green")
turtle.right(120)
turtle.forward(300)
turtle.right(120)
turtle.forward(300)
turtle.right(120)
turtle.forward(300)
turtle.done()